#This application is a server, it should act as a client and it should
#try to connect to itself - we need to configure in such away

server:
  port: 8761

spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # we made it not to registry with the Eureka
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  here hostname is localhost and port is 8761
